/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme.ts
 * Command: astryx theme build src/theme.ts
 * CLI: @astryxdesign/cli@0.3.0
 * Core: @astryxdesign/core@0.3.0
 */

/**
 * clockit theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { clockitTheme } from './clockit';
 *   import './clockit.css';
 */
export const clockitTheme = {
  name: 'clockit',
  __built: true,
  tokens: {
    "--color-accent": "light-dark(#00286E, #8AB0FF)"
  },

};
